[package]
name = "timesman-app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
eframe = "0.29.1"
egui = "0.29.1"
egui-file-dialog = "0.7.0"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.131"
